import perfil from "../../assets/proyectos/ab.jpg";
import blog from "../../assets/proyectos/blogrecetas.jpg";
import sanjorge from "../../assets/proyectos/hostalsanjorge.jpg";

const proyectos = [
    {
        id: 111,
        imagen: perfil,
        nombre: "Ambiente Bohemio",
        tipo: "Aplicación web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "Realizado como proyecto final del curso Desarrollador FullStack dictado por RollingCodeSchool",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
        enlace: "https://ambiente-bohemio-restaurante.netlify.app/",
    },
    {
        id: 222,
        imagen: sanjorge,
        nombre: "Hostal San Jorge",       
        tipo: "Sitio web",
        descripcion: "Sitio web realizado para el hostal san jorge de cafayate, provincia de salta",
        proyecto: "Freelance",
        finalidad: "Este sitio web fue realizado para que el hostal llegue a más personas a través del sitio",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/HostalSanJorgeCafayate",
        enlace: "https://hostalsanjorgecafayate.netlify.app/",
    },
    {
        id: 333,
        imagen: blog,
        nombre: "Blog de recetas",       
        tipo: "Blog",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/frontendBlogDeRecetas",
        enlace: "https://rincondeplaceresgastronomicos-rpg.netlify.app/",
    },
    {
        id: 444,
        imagen: "",
        nombre: "Temporizador",       
        tipo: "Aplicación web",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/Temporizador",
        enlace: "https://temporizador-online-bmr.netlify.app/",
    },
    {
        id: 555,
        imagen: "",
        nombre: "La Parrillada",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/LaParrillada",
        enlace: "https://r-parrillada-resto.netlify.app/",
    },
    {
        id: 666,
        imagen: "",
        nombre: "Rolling Shoes Store",       
        tipo: "Sitio web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/RollingShoesStore",
        enlace: "https://rollingshoesstore-rss.netlify.app/",
    },
    {
        id: 777,
        imagen: "",
        nombre: "Technical Documentation",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/TechnicalDocumentation",
        enlace: "https://technicaldocumentation-bmr.netlify.app/",
    },
    {
        id: 888,
        imagen: "",
        nombre: "Rolling Bank",       
        tipo: "Sitio web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/RollingBank",
        enlace: "https://rolling-bank-rb.netlify.app/",
    },
    {
        id: 999,
        imagen: "",
        nombre: "Landing Page",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/LandingPage",
        enlace: "https://landingpage-bmr.netlify.app/",
    },
    {
        id: 1010,
        imagen: "",
        nombre: "Películas",       
        tipo: "Otro",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/CRUD_Peliculas",
        enlace: "https://crudpeliculas-bmr.netlify.app/",
    }
]

export default proyectos;