import ab from "../../assets/proyectos/ambientebohemio.webp";
import blog from "../../assets/proyectos/blog.avif";
import temp from "../../assets/proyectos/temp.jpg";
import rss1 from "../../assets/proyectos/rss1.jpg";
import parrillada from "../../assets/proyectos/laparrillada.jpg";
import technicaldoc from "../../assets/proyectos/technicaldoc.jpg";
import rollingbank from "../../assets/proyectos/rollingbank.jpg";
import trombones from "../../assets/proyectos/trombones.jpg";
import blogrecetas from "../../assets/proyectos/blogrecetas.jpg";
import peliculas from "../../assets/proyectos/peliculas.jpg";
import sanjorge from "../../assets/frente.webp";
import clima from "../../assets/proyectos/clima.jpg";
import wpp from "../../assets/proyectos/wpp.jpg"

const proyectos = [
    {
        id: 111,
        imagen: ab,
        nombre: "Ambiente Bohemio",
        tipo: "Aplicación web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "Realizado como proyecto final del curso Desarrollador FullStack dictado por RollingCodeSchool",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
        enlace: "https://ambiente-bohemio-restaurante.netlify.app/",
    },
    {
        id: 222,
        imagen: sanjorge,
        nombre: "Hostal San Jorge",       
        tipo: "Sitio web",
        descripcion: "Sitio web realizado para el hostal san jorge de cafayate, provincia de salta",
        proyecto: "Freelance",
        finalidad: "Este sitio web fue realizado para que el hostal llegue a más personas a través del sitio",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/HostalSanJorgeCafayate",
        enlace: "https://hostalsanjorgecafayate.netlify.app/",
    },
    {
        id: 333,
        imagen: blogrecetas,
        nombre: "Blog de recetas",       
        tipo: "Sitio web",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/frontendBlogDeRecetas",
        enlace: "https://rincondeplaceresgastronomicos-rpg.netlify.app/",
    },
    {
        id: 444,
        imagen: temp,
        nombre: "Temporizador",       
        tipo: "Aplicación web",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/Temporizador",
        enlace: "https://temporizador-online-bmr.netlify.app/",
    },
    {
        id: 555,
        imagen: parrillada,
        nombre: "La Parrillada",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/LaParrillada",
        enlace: "https://r-parrillada-resto.netlify.app/",
    },
    {
        id: 666,
        imagen: rss1,
        nombre: "Rolling Shoes Store",       
        tipo: "Sitio web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/RollingShoesStore",
        enlace: "https://rollingshoesstore-rss.netlify.app/",
    },
    {
        id: 777,
        imagen: technicaldoc,
        nombre: "Technical Documentation",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/TechnicalDocumentation",
        enlace: "https://technicaldocumentation-bmr.netlify.app/",
    },
    {
        id: 888,
        imagen: rollingbank,
        nombre: "Rolling Bank",       
        tipo: "Sitio web",
        descripcion: "",
        proyecto: "Grupal",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/RollingBank",
        enlace: "https://rolling-bank-rb.netlify.app/",
    },
    {
        id: 999,
        imagen: trombones,
        nombre: "Original Trombones",       
        tipo: "Landing Page",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/LandingPage",
        enlace: "https://landingpage-bmr.netlify.app/",
    },
    {
        id: 1010,
        imagen: peliculas,
        nombre: "Películas",       
        tipo: "Otro",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/CRUD_Peliculas",
        enlace: "https://crudpeliculas-bmr.netlify.app/",
    },
    {
        id: 1121,
        imagen: clima,
        nombre: "Clima",       
        tipo: "Aplicación web",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/webDeClima_API_react",
        enlace: "https://ejercicio13-bmr.netlify.app/",
    },
    {
        id: 1267,
        imagen: wpp,
        nombre: "Pantalla WhatsApp Web",       
        tipo: "Challenge",
        descripcion: "",
        proyecto: "Individual",
        finalidad: "",
        objetivos:"",
        responsabilidades:[""],
        github: "https://github.com/brunomry/challengeRollingCode",
        enlace: "https://challenge-rc-bmr.netlify.app/",
    }
]

export default proyectos;