import laburandoando from "../assets/projects-images/laburandoando.png";
import ab from "../assets/projects-images/ambientebohemio.webp";
import sanjorge from "../assets/projects-images/sanjorge.webp";
import rafter from "../assets/projects-images/rafter.webp";
import imgtfi from "../assets/projects-images/tfi.png";
import ig from "../assets/projects-images/ig.png";
import netflixcard from "../assets/projects-images/netflixcard.png";
import netflix from "../assets/projects-images/netflix.png";
import buenbit from "../assets/projects-images/buenbit.png";
import buenbitcard from "../assets/projects-images/buenbitcard.png";
import tfi from "../assets/projects-images/trabajofinal-diseñodesistemas.pdf";
import lavanderia from "../assets/projects-images/lavanderia.jpg";
import alojamientos from "../assets/projects-images/alojamientos.jpg";
import lavanderiavideo from "../assets/projects-images/videos/lavanderia.mp4";

const projects = [
   {
    id: 123,
    image: lavanderia,
    category: "Lavandería",
    name: "Lavandería Arcoiris",
    type: "Aplicación web",
    area: "frontend",
    date: "Noviembre 2025",
    duration: "4 semanas",
    last_update: "Enero 2026",
    status: "Mantenimiento activo",
    project: "Académico/Freelance",
    description: "Aplicación web diseñada para facilitar la gestión diaria de una lavandería, centralizando en un solo sistema el control de órdenes, prendas, clientes y usuarios. Permite registrar y administrar cada trabajo de forma ordenada, agilizando la atención al cliente y reduciendo errores en el seguimiento de ordenes. A través de una interfaz clara e intuitiva, el personal puede buscar órdenes por nombre, código o fecha, gestionar prendas y mantener actualizada la información de los clientes. El sistema genera automáticamente comprobantes de entrega y carnets virtuales para los clientes, los cuales pueden compartirse directamente por WhatsApp, mejorando la comunicación y la experiencia del usuario final. La aplicación está pensada para negocios que necesitan optimizar tiempos, mantener un control interno eficiente y ofrecer una atención más profesional, con una base sólida para seguir creciendo e incorporar nuevas funcionalidades en el futuro.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "Redux-Toolkit" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Sweet-Alert" },
      { name: "Netlify" },
    ],
    responsabilities: [
      "Diseño e implementación de la arquitectura frontend con React y Redux Toolkit",
      "Desarrollo de formularios complejos utilizando React Hook Form con validaciones condicionales",
      "Integración del frontend con la API REST desarrollada en Node.js y Express",
      "Gestión de estado global y asincronismo mediante Redux Toolkit y createAsyncThunk",
      "Implementación de filtros dinámicos para órdenes, clientes y prendas",
      "Manejo de errores y feedback visual al usuario con SweetAlert",
      "Optimización de la experiencia de usuario y responsividad con TailwindCSS",
      "Despliegue y mantenimiento de la aplicación en Netlify",
      "Generación y prueba de remitos en formato imagen desde el backend",
    ],

    characteristics: [
      "Arquitectura modular basada en dominios (órdenes, clientes, prendas, usuarios)",
      "Interfaz moderna, responsive y orientada a uso administrativo",
      "Validaciones de negocio en frontend y backend para asegurar integridad de datos",
      "Sistema de filtrado eficiente para grandes volúmenes de órdenes",
      "Generación automática de remitos en formato imagen",
      "Generación automática de carnet virtual del cliente en formato imagen",
      "Comunicación cliente-servidor mediante API REST segura",
      "Proyecto escalable preparado para futuras integraciones como reportes y estadísticas, gestión de stock, gestión de pagos, entre otras",
    ],
    features: [
      "Inicio de sesión de usuarios administradores",
      "Gestión de ordenes, prendas, clientes y usuarios administradores",
      "Filtros para ordenes: nombre de cliente, código y fecha de orden",
      "Filtro para prendas: por nombre",
      "Filtro para clientes: por nombre",
      "Validaciones y manejo de errores",
      "Generación de imagen para remito",
      "Generación de imagen para carnet virtual del cliente",
      "Compartir comprobante de orden vía WhatsApp",
      "Compartir carnet de cliente vía WhatsApp",
    ],

    video: lavanderiavideo,
    github: "",
    link: "",
  },
  {
    id: 223,
    image: rafter,
    category: "Construcción",
    name: "Rafter Constructora",
    type: "Landing page",
    area: "frontend",
    date: "Noviembre 2025",
    duration: "4 semanas",
    last_update: "Diciembre 2025",
    status: "Mantenimiento activo",
    project: "Freelance",
    description: "Landing page desarrollada para Rafter Constructora, diseñada para fortalecer su presencia en Internet y aumentar la visibilidad de la empresa en San Miguel de Tucumán y alrededores. La página presenta un diseño moderno y adaptado a todo tipo de dispositivos, permitiendo que los clientes encuentren fácilmente información sobre los servicios y proyectos de la constructora. Además, está preparada y optimizada para buscadores, lista para potenciar su posicionamiento, facilitando que la empresa aparezca en los resultados de búsqueda y mejorando el contacto con clientes potenciales.",
    technologies: [
      { name: "Figma" },
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      // { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
      { name: "DonWeb" },
      { name: "Vercel" },
    ],
    responsabilities: [
      "Diseño de interfaz con Figma",
      "Posicionamiento en Google con palabras clave relevantes",
      // "Integración con 'Sitio web' de Google My Business",
      "Registro y gestión de dominio .com.ar mediante DonWeb y Vercel",
    ],
    characteristics: [
      "Diseño responsive con TailwindCSS",
      "Optimización SEO para buscadores",
    ],
    features: [],
    video: "",
    github: "",
    link: "https://rafterconstructora.com.ar/",
  },
  {
    id: 222,
    image: sanjorge,
    category: "Alojamiento",
    name: "Hostal San Jorge",
    type: "Sitio web",
    area: "frontend",
    date: "Enero 2024",
    duration: "8 semanas",
    last_update: "Noviembre 2025",
    status: "Mantenimiento activo",
    project: "Freelance",
    description: "Sitio web desarrollado para mejorar la visibilidad online del Hostal San Jorge en Cafayate, permitiendo que los visitantes se informen fácilmente sobre habitaciones, servicios y comodidades. Actualmente, los usuarios pueden realizar consultas y solicitudes de reserva mediante formularios y WhatsApp, mejorando la comunicación directa y la experiencia del cliente. El sitio está optimizado para buscadores y preparado para SEO, con el objetivo de aparecer en los primeros resultados de Google. Próximamente, el sitio permitirá que los usuarios se registren, inicien sesión y realicen reservas de manera directa.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Netlify" },
      { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
    ],
    responsabilities: [
      "Posicionamiento en Google con palabras clave relevantes",
      "Optimización de velocidad y rendimiento de la app",
      "Formularios de contacto y reserva para usuarios",
      // "Implementación de traducción de español a inglés",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de imágenes de alta calidad con fotógrafa",
      "Buenas prácticas semánticas",
    ],
    characteristics: [
      "Optimización SEO y rendimiento de la app",
      "Registro y gestión de dominio .com mediante Hostinger y Netlify",
      "Registro de dominio en Google Search Console",
      "Contratación de fotógrafa",
    ],
    features: [
      "Formulario de reserva",
      "Formulario de contacto",
      "Consultas por WhatsApp",
      // "Traducción de contenido a inglés",
    ],
    video: "",
    github: "",
    link: "https://hostalsanjorgecafayate.com/",
  },
 
  // {
  //   id: 123,
  //   image: ab,
  //   category: "Restaurante",
  //   name: "Ambiente Bohemio",
  //   type: "Aplicación web",
  //   area: "frontend",
  //   date: "Marzo 2024",
  //   duration: "4 semanas",
  //   last_update: "Marzo 2025",
  //   status: "Actualizando",
  //   project: "Educativo",
  //   description:
  //     "Aplicación web para restaurante donde los usuarios se registran, inician sesión y realizan pedidos online con integración de pago.",
  //   technologies: [
  //     { name: "React" },
  //     { name: "Bootstrap5" },
  //     { name: "Javascript" },
  //     { name: "CSS3" },
  //     { name: "React Bootstrap" },
  //     { name: "React Hook Form" },
  //     { name: "React Router" },
  //     { name: "Sweet-Alert" },
  //     { name: "Node js" },
  //     { name: "Express js" },
  //     { name: "MongoDB" },
  //     { name: "Mongoose" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Trello" },
  //     { name: "Scrumban" },
  //     { name: "Draw.io" },
  //     { name: "Postman" },
  //   ],
  //   responsabilities: [
  //     "Rol de scrummaster: organización de backlog, descripción de tareas y guía del equipo.",
  //     "Mejoras de diseño, funcionalidad de pago y estructura de proyecto (octubre 2024).",
  //     "Mockups de interfaces con Draw.io.",
  //     "Maquetado de páginas: Inicio, Detalle producto, Administración, Historial de pedidos.",
  //     "Funcionalidades: listado de productos por categoría, filtrado por name, descarga de PDF en menú.",
  //     "Colaboración en integración de API de MercadoPago para pagos.",
  //   ],
  //   characteristics: ["Aplicación de Metodología Scrumban"],
  //   features: [
  //     "Registro e inicio de sesión de usuarios",
  //     "Visualización de productos",
  //     "Carrito de compras y pago con MercadoPago",
  //     "Filtrado de productos por categoría o name",
  //     "Descarga de PDF del menú",
  //     "Gestión de usuarios, productos y pedidos",
  //     "Backend con despliegue en Vercel y API en Node/Express",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
  //   link: "https://ambiente-bohemio-restaurante.netlify.app/",
  // },

  // {
  //   id: 111,
  //   image: laburandoando,
  //   category: "Portal de Trabajo",
  //   name: "LaburandoAndo",
  //   type: "Aplicación web",
  //   area: "frontend",
  //   date: "Julio 2024",
  //   duration: "6 semanas",
  //   last_update: "-",
  //   status: "Finalizado",
  //   project: "Educativo",
  //   description:
  //     "Esta idea de proyecto surge de la necesidad de contar con un portal específico que pueda reunir una amplia variedad de trabajos autónomos, brindando visibilidad y oportunidades a profesionales independientes que buscan ampliar su clientela y conectar con nuevos clientes. La aplicación está diseñada para facilitar la búsqueda y contratación de servicios.",
  //   technologies: [
  //     { name: "React" },
  //     { name: "Redux-Toolkit" },
  //     { name: "Bootstrap5" },
  //     { name: "Javascript" },
  //     { name: "CSS3" },
  //     { name: "React Bootstrap" },
  //     { name: "React Hook Form" },
  //     { name: "React Router" },
  //     { name: "React-Icons" },
  //     { name: "Sweet-Alert" },
  //     { name: "Axios" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Draw.io" },
  //     { name: "NodeJS" },
  //     { name: "ExpressJS" },
  //     { name: "MongoDB" },
  //     { name: "Postman" },
  //     { name: "Netlify" },
  //     { name: "Render" },
  //     { name: "Trello" },
  //     { name: "Scrum" },
  //   ],
  //   responsabilities: [
  //     "Scrummaster: definición de sprints, organización del backlog y descripción de tareas.",
  //     "Mockups de interfaces con Draw.io.",
  //     "Definición de requerimientos de usuario",
  //     "Colaboración en desarrollo responsive de toda la aplicación.",
  //     "Maquetado de páginas: Profesionales, Opciones de Registro, Publicaciones, Quienes Somos, Soporte Admin, Sidebar.",
  //     "Funcionalidades: Visualización de comentarios, eliminación de comentarios como admin, creación de publicaciones y perfil profesional.",
  //     "Implementación de buenas prácticas semánticas",
  //     "Resolución de issues en github",
  //     "Implementación de lineamientos de arquitectura basada en dominios",
  //   ],
  //   characteristics: [
  //     "Aplicación de Metodología Scrum",
  //     "Arquitectura basada en dominios",
  //   ],
  //   features: [
  //     "Registro e inicio de sesión de usuarios",
  //     "Visualización de anuncios de profesionales",
  //     "Paginación para anuncios de profesionales",
  //     "Visualización detallada de anuncio de profesional",
  //     "Gestión de perfil para profesionales",
  //     "Gestión de publicaciones para profesionales",
  //     "Filtrado de profesionales por nombre, ubicación y categoría",
  //     "Publicación de comentario y valoración para clientes",
  //     "Envío de mensajes de soporte para profesionales",
  //     "Gestión de mensajes reportados por profesionales",
  //     "Gestión de usuarios y categorías",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/LaburandoAndo",
  //   link: "https://laburando-ando.netlify.app/",
  // },
  {
    id: 666,
    image: imgtfi,
    category: "Documentación",
    name: "Sistema de Gestión de Reservas - Hostal San Jorge",
    type: "Análisis y Diseño de sistemas",
    area: "académico",
    date: "Noviembre 2020",
    duration: "5 meses",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Proyecto académico orientado al diseño de un sistema de gestión de reservas para el Hostal San Jorge. Incluye análisis de requerimientos, casos de uso, modelado UML, diseño de base de datos y prototipos de interfaz.",
    technologies: [
      { name: "Análisis de requerimientos" },
      { name: "Casos de uso" },
      { name: "Modelado UML" },
      { name: "Modelado de base de datos" },
      { name: "Prototipos de interfaz" },
      { name: "Draw.io" },
      { name: "Documentación técnica" },
      { name: "Balsamiq" },
    ],
    responsabilities: [
      "Relevamiento de requerimientos.",
      "Redacción de casos de uso y contratos",
      "Diagramas UML: diagrama de casos de uso, modelo de dominio, diagrama de actividades, diagrama de clases, diagramas de secuencia, diagramas de colaboración, diagrama de transición de estados.",
      "Modelado de base de datos (Modelo Entidad-Relación y Modelo relacional).",
      "Diseño de prototipos de interfaz del sistema.",
      "Contribución a la documentación general del proyecto final.",
    ],
    features: [],
    characteristics: [
      "Sistema propuesto para gestionar reservas, clientes y habitaciones.",
      "Casos de uso detallados para cada módulo del sistema.",
      "Modelos UML completos para visualizar procesos y entidades.",
    ],
    video: "",
    file: tfi,
    github: "",
    link: "",
  },
  {
    id: 779,
    image: lavanderia,
    category: "Lavandería",
    name: "API Restful para Lavanderías",
    type: "API REST",
    area: "backend",
    date: "Noviembre 2025",
    duration: "4 semanas",
    last_update: "Enero 2026",
    status: "Mantenimiento activo",
    project: "Freelance",
    description:
      "API RESTful desarrollada para la gestión interna de lavanderías. En esta API se pueden gestionar órdenes, prendas, clientes y usuarios administradores, generación de remitos mediante Pureimage y almacenamiento con Cloudinary, autenticación segura y validaciones robustas. La API está diseñada para optimizar las operaciones diarias de una lavandería. Se encuentra en continuo desarrollo para agregar nuevas funcionalidades según las necesidades del cliente.",
    technologies: [
      { name: "Node js" },
      { name: "Express js" },
      { name: "Express validator" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Postman" },
      { name: "JSON Web Token" },
      { name: "Cloudinary" },
      { name: "Bcrypt" },
      { name: "Pureimage" },
    ],
    responsabilities: [
      "Implementación de rutas, controladores, servicios, repositorios y valiaciones para ordenes, prendas, clientes y usuarios administradores.",
      "Gestión de autenticación y autorización de usuarios administradores.",
      "Validación de datos y manejo de errores.",
      "Pruebas de API con Postman y documentación de endpoints.",
    ],
    features: [
      "CRUD de ordenes, prendas, clientes y usuarios.",
      "Autenticación con tokens JWT.",
      "Endpoints organizados y documentados para fácil integración con frontend.",
      "Validaciones y manejo de errores completo.",
    ],
    characteristics: [],
    video: "",
    github: "",
    link: "",
  },
  {
    id: 770,
    image: alojamientos,
    category: "Alojamientos",
    name: "API Restful para Alojamientos",
    type: "API REST",
    area: "backend",
    date: "Octubre 2025",
    duration: "12 semanas",
    last_update: "Diciembre 2025",
    status: "En continuo desarrollo",
    project: "Freelance",
    description:
      "API RESTful desarrollada para la gestión interna de alojamientos. En esta API se pueden gestionar servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes, administradores y autenticación para administradores y huéspedes. La API está diseñada para optimizar todos los procesos de un alojamiento. Además también permitirá que los usuarios puedan realizar reservas. Se encuentra en continuo desarrollo para agregar nuevas funcionalidades como reportes, gestión de stock, gestión de promociones/descuentos, notificaciones, turnos para el desayuno, entre otras.",
    technologies: [
      { name: "Node js" },
      { name: "Express js" },
      { name: "Express validator" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Postman" },
      { name: "JSON Web Token" },
      { name: "Nodemailer" },
      { name: "Cloudinary" },
      { name: "MercadoPago" },
      { name: "Stripe" },
      { name: "Bcrypt" },
      { name: "Cookie-parser" },
    ],
    responsabilities: [
      "Implementación de rutas, controladores, servicios, repositorios y valiaciones para autenticación, servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes y usuarios administradores.",
      "Gestión de autenticación y autorización de usuarios administradores y huéspedes.",
      "Validación de datos y manejo de errores.",
      "Pruebas de API con Postman y documentación de endpoints.",
    ],
    features: [
      "CRUD de servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes y usuarios.",
      "Autenticación con tokens JWT.",
      "Endpoints organizados y documentados para fácil integración con frontend.",
      "Validaciones y manejo de errores completo.",
    ],
    characteristics: [],
    video: "",
    github: "",
    link: "",
  },
  // {
  //   id: 777,
  //   image: ab,
  //   category: "Restaurante",
  //   name: "API Restful Restaurante Ambiente Bohemio",
  //   type: "API REST",
  //   area: "backend",
  //   date: "Marzo 2024",
  //   duration: "4 semanas",
  //   last_update: "Octubre 2025",
  //   status: "Actualizando",
  //   project: "Educativo",
  //   description:
  //     "API RESTful desarrollada para gestionar un restaurante, incluyendo usuarios, productos, pedidos y autenticación, con buenas prácticas de organización de rutas y controladores.",
  //   technologies: [
  //     { name: "Node js" },
  //     { name: "Express js" },
  //     { name: "Express-validator" },
  //     { name: "MongoDB" },
  //     { name: "Mongoose" },
  //     { name: "Javascript" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Postman" },
  //     { name: "JSON Web Token" },
  //     { name: "Bcrypt" },
  //     { name: "Vercel"}
  //   ],
  //   responsabilities: [
  //     "Implementación de rutas y controladores para usuarios, productos y pedidos.",
  //     "Gestión de autenticación y autorización de usuarios.",
  //     "Validación de datos y manejo de errores.",
  //     "Pruebas de API con Postman y documentación de endpoints.",
  //   ],
  //   features: [
  //     "CRUD de usuarios, productos y pedidos.",
  //     "Autenticación con tokens JWT.",
  //     "Endpoints organizados y documentados para fácil integración con frontend.",
  //     "Validaciones y manejo de errores completo.",
  //   ],
  //   characteristics: [
  //     "Aplicación de Metodología Scrum",
  //     "Despliegue en Vercel",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/API_restaurante",
  //   link: "",
  // },

  {
    id: 888,
    image: netflixcard,
    category: "Interfaz mobile en Figma",
    name: "Vista principal Instagram - Netflix",
    type: "Diseño UI",
    area: "diseño",
    date: "Mayo 2025",
    duration: "1 semana",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Desafío de diseño propuesto en curso de youtube sobre Figma brindado por uxcristopher que consistía en diseñar la interfaz principal de Instagram y Netflix.",
    technologies: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilities: [
      "Primeros diseños en Figma",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño replicado de aplicaciones reconocidas (Netflix/Instagram)",
    ],
    features: [],
    characteristics: [
      "Diseño de interfaz principal de Instagram y Netflix",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    video: "",
    github: "",
    images: [ig, netflix],
    link: "https://www.figma.com/design/2DxaPRLCWwSmJjCte0qdm8/Dise%C3%B1os?node-id=0-1&t=iT0lRymaWSvM4QJJ-1",
  },
  {
    id: 999,
    image: buenbitcard,
    category: "Interfaz mobile en Figma",
    name: "Vista Home - App BuenBit",
    type: "Diseño UI",
    area: "diseño",
    date: "Agosto 2025",
    duration: "3 días",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Desafío de diseño propuesto por BuenBit que consistía en realizar un diseño original de la Home de su aplicación y publicarlo en X con el hashtag #FigmaEnBuenBit. El desafío estaba pensado para diseñadores pero cualquier persona podía participar.",
    technologies: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilities: [
      "Desafío de diseño",
      "Publicación en X con hashtag #FigmaEnBuenBit",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño inspirado en la Home de app BuenBit",
    ],
    features: [],
    characteristics: [
      "Diseño de la Home de BuenBit",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    images: [buenbit],
    video: "",
    github: "",
    link: "https://www.figma.com/design/joPj1Ky1SUs3O37tQVotqg/HomeBuenbit?node-id=1-689&t=ar7HVNYCBf2uByns-1",
  },
];

export default projects;
