import laburandoando from "../assets/projects-images/laburandoando.png";
import ab from "../assets/projects-images/ambientebohemio.webp";
import sanjorge from "../assets/projects-images/sanjorge.webp";
import rafter from "../assets/projects-images/rafter.webp";
import imgtfi from "../assets/projects-images/tfi.png";
import ig from "../assets/projects-images/ig.png";
import netflixcard from "../assets/projects-images/netflixcard.png";
import netflix from "../assets/projects-images/netflix.png";
import buenbit from "../assets/projects-images/buenbit.png";
import buenbitcard from "../assets/projects-images/buenbitcard.png";
import tfi from "../assets/projects-images/trabajofinal-diseñodesistemas.pdf";
import lavanderia from "../assets/projects-images/lavanderia.jpg";
import alojamientos from "../assets/projects-images/alojamientos.jpg";
import lavanderiavideo from "../assets/projects-images/videos/lavanderia.mp4";
import hamburgueseriaImage from "../assets/projects-images/hamburgueseria.jpg";
import dieteticaImage from "../assets/projects-images/dietetica-sin-tacc.jpg";
import localRopaImage from "../assets/projects-images/local-ropa.jpg";
import servicioTecnicoImage from "../assets/projects-images/servicio-tecnico.jpg";

const projects = [
  {
    id: 124,
    image: hamburgueseriaImage,
    category: "Gastronomía",
    name: "Sistema de pedidos para bares y restaurantes",
    type: "Aplicación web · SaaS",
    area: "frontend",
    date: "Julio 2026",
    duration: "En desarrollo",
    last_update: "Agosto 2026",
    status: "En desarrollo",
    project: "Freelance",
    problem: "Los bares y restaurantes necesitan concentrar su menú y la recepción de pedidos en un canal más ordenado, sin perder la cercanía y simplicidad de WhatsApp.",
    outcome: "La aplicación permite que cada cliente arme su pedido desde la web y lo envíe por WhatsApp, mientras el negocio administra productos y consulta los pedidos desde un panel privado.",
    outcomeLabel: "Objetivo del producto",
    outcomeDetail: "Reducir la fricción al tomar pedidos y dar al negocio control diario sobre qué productos se muestran y cuáles están disponibles.",
    description: "Aplicación web SaaS en desarrollo para digitalizar los pedidos de bares y restaurantes. Los clientes consultan el menú, arman su pedido y lo envían por WhatsApp. El administrador puede ver los pedidos del día, consultar el historial por fecha, nombre o código, cargar productos y actualizar su disponibilidad y visibilidad según el menú de cada jornada.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "Redux-Toolkit" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Sweet-Alert" },
      { name: "Netlify" },
      { name: "Node js" },
      { name: "Express js" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "JSON Web Token" },
      { name: "Cloudinary" },
      { name: "Bcrypt" },
      { name: "Vercel" },
    ],
    responsabilities: ["Diseño del flujo de compra desde dispositivos móviles.", "Desarrollo del panel privado para la gestión diaria.", "Implementación de búsquedas por fecha, nombre y código.", "Gestión de productos, disponibilidad y publicación del menú.", "Integración del pedido con WhatsApp."],
    features: ["Menú digital y armado de pedidos.", "Envío del pedido por WhatsApp.", "Inicio de sesión para administradores.", "Pedidos del día e historial con filtros.", "Alta y edición de productos.", "Estados disponible y agotado.", "Publicación u ocultamiento de productos."],
    characteristics: ["Producto SaaS orientado a pequeños negocios gastronómicos.", "Experiencia responsive con prioridad móvil.", "Base preparada para incorporar nuevas funciones."],
    video: "", github: "", link: "",
  },
  // {
  //   id: 125,
  //   image: dieteticaImage,
  //   category: "Comercio",
  //   name: "Tienda online de productos sin TACC",
  //   type: "Aplicación web · SaaS",
  //   area: "frontend",
  //   date: "Agosto 2026",
  //   duration: "En desarrollo",
  //   last_update: "-",
  //   status: "En desarrollo",
  //   project: "Freelance",
  //   problem: "La clienta necesita trasladar su actividad a un modelo de venta desde casa sin perder el vínculo con sus clientes.",
  //   outcome: "La solución propone un canal propio para exhibir productos sin TACC, recibir pedidos y mantener activa la venta sin depender de un espacio comercial físico.",
  //   outcomeLabel: "Impacto esperado",
  //   outcomeDetail: "Dar continuidad al emprendimiento, reducir costos fijos y construir una base digital que pueda crecer con nuevas herramientas de venta y gestión.",
  //   description: "Aplicación web SaaS en desarrollo para un almacén/dietética de productos sin TACC. El proyecto acompaña la transición desde el local físico hacia la venta desde casa mediante un catálogo accesible, un proceso de pedido simple y una administración centralizada.",
  //   technologies: [
  //     { name: "React" },
  //     { name: "TailwindCSS" },
  //     { name: "Redux-Toolkit" },
  //     { name: "Javascript" },
  //     { name: "CSS3" },
  //     { name: "React Hook Form" },
  //     { name: "React Router" },
  //     { name: "Sweet-Alert" },
  //     { name: "Netlify" },
  //     { name: "Node js" },
  //     { name: "Express js" },
  //     { name: "MongoDB" },
  //     { name: "Mongoose" },
  //     { name: "JSON Web Token" },
  //     { name: "Cloudinary" },
  //     { name: "Bcrypt" },
  //     { name: "Vercel" },
  //   ],    responsabilities: ["Relevamiento de las necesidades comerciales.", "Diseño de una experiencia de compra accesible desde celulares.", "Desarrollo del catálogo y del flujo de pedidos.", "Diseño de una base escalable para futuras funcionalidades."],
  //   features: ["Catálogo digital de productos sin TACC.", "Consulta de disponibilidad y armado de pedidos.", "Gestión centralizada de productos.", "Experiencia orientada a compras desde el celular."],
  //   characteristics: ["Producto SaaS para sostener la continuidad de un comercio local.", "Proyecto evolutivo preparado para sumar herramientas comerciales."],
  //   video: "", github: "", link: "",
  // },
  {
    id: 126,
    image: localRopaImage,
    category: "Comercio",
    name: "Tienda online para Blanquería y Lencería",
    type: "Aplicación web · SaaS",
    area: "frontend",
    date: "Agosto 2026",
    duration: "En desarrollo",
    last_update: "-",
    status: "En desarrollo",
    project: "Freelance",
    problem: "El comercio depende de estados de WhatsApp, historias de Instagram y un catálogo externo que muchos clientes no consultan, lo que limita el alcance y obliga a publicar el mismo contenido repetidamente.",
    outcome: "La aplicación reunirá el catálogo y el armado del pedido en un espacio propio, permitiendo que el cliente agregue productos al carrito y envíe la solicitud final por WhatsApp.",
    outcomeLabel: "Impacto esperado",
    outcomeDetail: "Transformar publicaciones efímeras en un canal de ventas permanente, ampliar el alcance del comercio y facilitar que los clientes encuentren sus productos.",
    description: "Aplicación web SaaS en desarrollo para pequeño local de Blanquería y Lencería. Combina un catálogo digital con páginas informativas y un carrito de compras para que los clientes armen su pedido y lo envíen por WhatsApp. La solución busca construir una presencia digital propia, reducir la dependencia de publicaciones temporales en WhatsApp e Instagram y dejar preparada la incorporación de pagos online en una etapa futura.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "Redux-Toolkit" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Sweet-Alert" },
      { name: "Netlify" },
      { name: "Node js" },
      { name: "Express js" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "JSON Web Token" },
      { name: "Cloudinary" },
      { name: "Bcrypt" },
      { name: "Vercel" }
    ],
    responsabilities: ["Análisis del proceso actual de difusión y venta.", "Diseño del catálogo, el carrito y las páginas institucionales.", "Desarrollo del catálogo y del flujo de pedido hacia WhatsApp.", "Preparación de una arquitectura escalable."],
    features: ["Catálogo de prendas y variantes.", "Carrito de compras.", "Envío del pedido por WhatsApp.", "Páginas informativas del comercio.", "Gestión de productos y disponibilidad.", "Base preparada para incorporar pagos online en el futuro."],
    characteristics: ["Catálogo, carrito y sitio institucional en una misma experiencia.", "Canal de ventas propio y responsive.", "Producto SaaS preparado para evolucionar."],
    video: "", github: "", link: "",
  },
  {
    id: 127,
    image: servicioTecnicoImage,
    category: "Servicio técnico",
    name: "Comprobante online para servicio técnico de celulares",
    type: "Herramienta web",
    area: "frontend",
    date: "Agosto 2026",
    duration: "3 días",
    last_update: "Agosto 2026",
    status: "Funcional",
    project: "Freelance",
    problem: "El servicio técnico no contaba con entrega de comprobantes y necesitaban una alternativa rápida y accesible para evitar problemas de comunicación con los clientes al recibir o entregar equipos.",
    outcome: "Se creó una herramienta online para generar comprobantes en PDF con la información esencial de cada equipo y trabajo recibido.",
    outcomeLabel: "Resultado comprobado",
    outcomeDetail: "El comprobante ya está en uso por el local: agiliza la recepción y entrega de equipos, mejora la presentación de la información al cliente y ayuda a evitar problemas de comunicación sobre el estado y las condiciones de cada dispositivo.",
    description: "Herramienta web creada para servicio técnico de celulares para simplificar la generación de comprobantes de recepción y servicio técnico. Centraliza los datos necesarios y produce un comprobante digital en PDF, listo para impresión.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Netlify" },
      { name: "Codex" },
    ],    responsabilities: ["Definición del problema y alcance.", "Diseño del flujo de carga.", "Construcción y validación de la herramienta con asistencia de Codex."],
    features: ["Carga de datos del cliente y del equipo.", "Generación de comprobante digital en formato PDF."],
    characteristics: ["Solución enfocada en una necesidad operativa concreta.", "Desarrollo iterativo asistido por inteligencia artificial."],
    video: "", github: "", link: "",
  },
 {
  id: 128,
  image: alojamientos,
  category: "Alojamiento",
  name: "Auditoría y propuesta de optimización web para alojamientos",
  type: "Auditoría y propuesta de optimización",
  area: "Auditoría y Optimización Web",
  date: "Septiembre 2026",
  duration: "Septiembre 2026",
  last_update: "-",
  status: "Finalizado",
  project: "Freelance",

  problem:
    "El sitio web reúne la oferta de dos alojamientos con características e identidades diferentes, pero la forma de organizar y comunicar la información limita la diferenciación entre ambas propuestas. También se detectaron oportunidades de mejora en la presentación de reseñas, ubicación, navegación, visibilidad en buscadores y recorrido hacia la consulta por WhatsApp.",

  outcome:
    "Se realizó una auditoría integral del sitio y se elaboró una propuesta de optimización orientada a fortalecer la identidad de ambos alojamientos, reorganizar la arquitectura de información, mejorar la experiencia de navegación y facilitar el recorrido hacia la consulta. El análisis también incluyó aspectos de posicionamiento orgánico, conversión y una revisión técnica preliminar.",

  outcomeLabel: "Resultado",

  outcomeDetail:
    "Se entregó un informe con hallazgos, prioridades y recomendaciones para mejorar la claridad, confianza, visibilidad y conversión del sitio, incluyendo una propuesta de reorganización que permite diferenciar ambos alojamientos dentro de una misma experiencia web.",

  description:
    "Auditoría y propuesta de optimización de un sitio web que reúne dos alojamientos turísticos de Cafayate. El trabajo incluyó el análisis de la propuesta de valor, identidad de cada alojamiento, arquitectura de información, navegación, contenidos, reseñas, ubicación, recorrido hacia WhatsApp, posicionamiento orgánico y aspectos técnicos del sitio. Como resultado se elaboró un informe con oportunidades de mejora priorizadas y una propuesta de reorganización que puede aplicarse sobre el sitio actual o servir como base para un futuro rediseño.",

  technologies: [
    { name: "Auditoría UX" },
    { name: "Arquitectura de información" },
    { name: "Optimización de conversión" },
    { name: "Análisis de contenidos" }
  ],

  responsabilities: [
    "Evaluación de la propuesta de valor y diferenciación entre ambos alojamientos.",
    "Análisis de la arquitectura de información, navegación y jerarquía de contenidos.",
    "Revisión del recorrido desde la exploración de los alojamientos hasta la consulta por WhatsApp.",
    "Análisis de la presencia de reseñas, ubicación y otros elementos de confianza.",
    "Evaluación de alternativas de organización: sitio único con marcas diferenciadas o sitios independientes.",
    "Priorización de oportunidades de mejora y elaboración del informe final de auditoría."
  ],

  features: [],

  characteristics: [
    "Auditoría realizada sobre un sitio web actualmente publicado.",
    "Análisis de dos alojamientos con identidades y propuestas de valor diferentes.",
    "Recomendaciones orientadas a mejorar claridad, confianza, visibilidad y conversión.",
    "Propuesta de reorganización de la experiencia web y diferenciación de ambas marcas.",
    "Informe final preparado como guía para una futura implementación."
  ],

  video: "",
  github: "",
  link: ""
},   {
    id: 123,
    image: lavanderia,
    category: "Lavandería",
    name: "Lavandería Arcoiris",
    type: "Aplicación web",
    area: "frontend",
    date: "Noviembre 2025",
    duration: "4 semanas",
    last_update: "Enero 2026",
    status: "En pausa",
    project: "Académico/Freelance",
    problem:
      "La operación diaria de una lavandería requiere registrar muchas prendas, clientes y estados de entrega. Cuando esa información se distribuye entre anotaciones o herramientas separadas, aumenta el tiempo de atención y el riesgo de cometer errores.",
    outcome:
      "La solución centraliza órdenes, prendas, clientes y usuarios en un mismo flujo de trabajo. También automatiza la generación de remitos y carnets virtuales listos para compartir por WhatsApp.",
    outcomeLabel: "Impacto esperado",
    outcomeDetail:
      "En una implementación comercial, permitiría reducir tareas manuales, agilizar la búsqueda y el seguimiento de órdenes y ofrecer al cliente una comunicación más clara y profesional.",
    description: "Aplicación web diseñada para facilitar la gestión diaria de una lavandería, centralizando en un solo sistema el control de órdenes, prendas, clientes y usuarios. Permite registrar y administrar cada trabajo de forma ordenada, agilizando la atención al cliente y reduciendo errores en el seguimiento de ordenes. A través de una interfaz clara e intuitiva, el personal puede buscar órdenes por nombre, código o fecha, gestionar prendas y mantener actualizada la información de los clientes. El sistema genera automáticamente comprobantes de entrega y carnets virtuales para los clientes, los cuales pueden compartirse directamente por WhatsApp, mejorando la comunicación y la experiencia del usuario final. La aplicación está pensada para negocios que necesitan optimizar tiempos, mantener un control interno eficiente y ofrecer una atención más profesional, con una base sólida para seguir creciendo e incorporar nuevas funcionalidades en el futuro.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "Redux-Toolkit" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Sweet-Alert" },
      { name: "Netlify" },
    ],
    responsabilities: [
      "Diseño e implementación de la arquitectura frontend con React y Redux Toolkit",
      "Desarrollo de formularios complejos utilizando React Hook Form con validaciones condicionales",
      "Integración del frontend con la API REST desarrollada en Node.js y Express",
      "Gestión de estado global y asincronismo mediante Redux Toolkit y createAsyncThunk",
      "Implementación de filtros dinámicos para órdenes, clientes y prendas",
      "Manejo de errores y feedback visual al usuario con SweetAlert",
      "Optimización de la experiencia de usuario y responsividad con TailwindCSS",
      "Despliegue y mantenimiento de la aplicación en Netlify",
      "Generación y prueba de remitos en formato imagen desde el backend",
    ],

    characteristics: [
      "Arquitectura modular basada en dominios (órdenes, clientes, prendas, usuarios)",
      "Interfaz moderna, responsive y orientada a uso administrativo",
      "Validaciones de negocio en frontend y backend para asegurar integridad de datos",
      "Sistema de filtrado eficiente para grandes volúmenes de órdenes",
      "Generación automática de remitos en formato imagen",
      "Generación automática de carnet virtual del cliente en formato imagen",
      "Comunicación cliente-servidor mediante API REST segura",
      "Proyecto escalable preparado para futuras integraciones como reportes y estadísticas, gestión de stock, gestión de pagos, entre otras",
    ],
    features: [
      "Inicio de sesión de usuarios administradores",
      "Gestión de ordenes, prendas, clientes y usuarios administradores",
      "Filtros para ordenes: nombre de cliente, código y fecha de orden",
      "Filtro para prendas: por nombre",
      "Filtro para clientes: por nombre",
      "Validaciones y manejo de errores",
      "Generación de imagen para remito",
      "Generación de imagen para carnet virtual del cliente",
      "Compartir comprobante de orden vía WhatsApp",
      "Compartir carnet de cliente vía WhatsApp",
    ],

    video: lavanderiavideo,
    github: "",
    link: "",
  },
  {
    id: 223,
    image: rafter,
    category: "Construcción",
    name: "Rafter Constructora",
    type: "Sitio web corporativo",
    area: "frontend",
    date: "Noviembre 2025",
    duration: "6 semanas",
    last_update: "Agosto 2026",
    status: "Mantenimiento activo",
    project: "Freelance",
    problem:
      "Rafter necesitaba una presencia digital profesional que acompañara el crecimiento de la empresa y permitiera explicar sus servicios y proyectos de manera clara a potenciales clientes.",
    outcome:
      "El sitio se encuentra publicado y es utilizado por la empresa como material de presentación comercial. Actualmente continúa evolucionando con nuevos cambios solicitados por el cliente para ampliar la información disponible.",
    outcomeLabel: "Resultado comprobado",
    outcomeDetail:
      "La web pasó a ser un recurso activo del proceso comercial: el equipo puede compartirla directamente con clientes que necesitan conocer mejor la empresa, sus servicios y su experiencia.",
    description: "Sitio web corporativo desarrollado para Rafter Constructora, diseñado para fortalecer su presencia en Internet y aumentar la visibilidad de la empresa en San Miguel de Tucumán y alrededores. Además de presentar sus servicios y trayectoria, cuenta con una sección de proyectos y páginas de detalle independientes para mostrar cada obra con mayor profundidad. La experiencia es moderna, responsive y está optimizada para buscadores, facilitando que potenciales clientes conozcan el trabajo de la constructora y puedan contactarla.",
    technologies: [
      { name: "Figma" },
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      // { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
      { name: "DonWeb" },
      { name: "Vercel" },
    ],
    responsabilities: [
      "Diseño de interfaz con Figma",
      "Posicionamiento en Google con palabras clave relevantes",
      // "Integración con 'Sitio web' de Google My Business",
      "Registro y gestión de dominio .com.ar mediante DonWeb y Vercel",
      "Evolución de la landing page original hacia un sitio web corporativo con nuevas secciones, catálogo de proyectos y páginas de detalle. (Agosto 2026)",
    ],
    characteristics: [
      "Diseño responsive con TailwindCSS",
      "Optimización SEO para buscadores",
    ],
    features: [
      "Presentación institucional de la empresa y sus servicios",
      "Sección de proyectos realizados",
      "Página de detalle individual para cada proyecto",
      "Contacto directo para potenciales clientes",
    ],
    video: "",
    github: "",
    link: "https://rafterconstructora.com.ar/",
  },
  {
    id: 222,
    image: sanjorge,
    category: "Alojamiento",
    name: "Hostal San Jorge",
    type: "Sitio web",
    area: "frontend",
    date: "Enero 2025",
    duration: "4 semanas",
    last_update: "Agosto 2026",
    status: "Mantenimiento activo",
    project: "Freelance",
    problem:
      "El hostal ya contaba con una web, pero su diseño anterior no comunicaba correctamente la calidad del alojamiento ni generaba suficiente confianza para que los visitantes iniciaran una consulta.",
    outcome:
      "Se rediseñó por completo la experiencia, mejorando la presentación de habitaciones, servicios y llamados a la acción, además de facilitar el contacto directo mediante WhatsApp y formularios.",
    outcomeLabel: "Resultado comprobado",
    outcomeDetail:
      "En los primeros dos meses del año, la nueva web generó más de 50 consultas directas por WhatsApp. Para un alojamiento local, este resultado demuestra que el rediseño no solo mejoró la imagen del negocio: también aumentó la confianza y produjo oportunidades comerciales concretas.",
    description: "Sitio web desarrollado para mejorar la visibilidad online del Hostal San Jorge en Cafayate, permitiendo que los visitantes se informen fácilmente sobre habitaciones, servicios y comodidades. Actualmente, los usuarios pueden realizar consultas y solicitudes de reserva mediante formularios y WhatsApp, mejorando la comunicación directa y la experiencia del cliente. El sitio está optimizado para buscadores y preparado para SEO, con el objetivo de aparecer en los primeros resultados de Google. Próximamente, el sitio permitirá que los usuarios se registren, inicien sesión y realicen reservas de manera directa.",
    technologies: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Netlify" },
      { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
    ],
    responsabilities: [
      "Posicionamiento en Google con palabras clave relevantes",
      "Optimización de velocidad y rendimiento de la app",
      "Formularios de contacto y reserva para usuarios",
      // "Implementación de traducción de español a inglés",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de imágenes de alta calidad con fotógrafa",
      "Buenas prácticas semánticas",
    ],
    characteristics: [
      "Optimización SEO y rendimiento de la app",
      "Registro y gestión de dominio .com mediante Hostinger y Netlify",
      "Registro de dominio en Google Search Console",
      "Contratación de fotógrafa",
    ],
    features: [
      "Formulario de reserva",
      "Formulario de contacto",
      "Consultas por WhatsApp",
      // "Traducción de contenido a inglés",
    ],
    video: "",
    github: "",
    link: "https://hostalsanjorgecafayate.com/",
  },
 
  // {
  //   id: 123,
  //   image: ab,
  //   category: "Restaurante",
  //   name: "Ambiente Bohemio",
  //   type: "Aplicación web",
  //   area: "frontend",
  //   date: "Marzo 2024",
  //   duration: "4 semanas",
  //   last_update: "Marzo 2025",
  //   status: "Actualizando",
  //   project: "Educativo",
  //   description:
  //     "Aplicación web para restaurante donde los usuarios se registran, inician sesión y realizan pedidos online con integración de pago.",
  //   technologies: [
  //     { name: "React" },
  //     { name: "Bootstrap5" },
  //     { name: "Javascript" },
  //     { name: "CSS3" },
  //     { name: "React Bootstrap" },
  //     { name: "React Hook Form" },
  //     { name: "React Router" },
  //     { name: "Sweet-Alert" },
  //     { name: "Node js" },
  //     { name: "Express js" },
  //     { name: "MongoDB" },
  //     { name: "Mongoose" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Trello" },
  //     { name: "Scrumban" },
  //     { name: "Draw.io" },
  //     { name: "Postman" },
  //   ],
  //   responsabilities: [
  //     "Rol de scrummaster: organización de backlog, descripción de tareas y guía del equipo.",
  //     "Mejoras de diseño, funcionalidad de pago y estructura de proyecto (octubre 2024).",
  //     "Mockups de interfaces con Draw.io.",
  //     "Maquetado de páginas: Inicio, Detalle producto, Administración, Historial de pedidos.",
  //     "Funcionalidades: listado de productos por categoría, filtrado por name, descarga de PDF en menú.",
  //     "Colaboración en integración de API de MercadoPago para pagos.",
  //   ],
  //   characteristics: ["Aplicación de Metodología Scrumban"],
  //   features: [
  //     "Registro e inicio de sesión de usuarios",
  //     "Visualización de productos",
  //     "Carrito de compras y pago con MercadoPago",
  //     "Filtrado de productos por categoría o name",
  //     "Descarga de PDF del menú",
  //     "Gestión de usuarios, productos y pedidos",
  //     "Backend con despliegue en Vercel y API en Node/Express",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
  //   link: "https://ambiente-bohemio-restaurante.netlify.app/",
  // },

  // {
  //   id: 111,
  //   image: laburandoando,
  //   category: "Portal de Trabajo",
  //   name: "LaburandoAndo",
  //   type: "Aplicación web",
  //   area: "frontend",
  //   date: "Julio 2024",
  //   duration: "6 semanas",
  //   last_update: "-",
  //   status: "Finalizado",
  //   project: "Educativo",
  //   description:
  //     "Esta idea de proyecto surge de la necesidad de contar con un portal específico que pueda reunir una amplia variedad de trabajos autónomos, brindando visibilidad y oportunidades a profesionales independientes que buscan ampliar su clientela y conectar con nuevos clientes. La aplicación está diseñada para facilitar la búsqueda y contratación de servicios.",
  //   technologies: [
  //     { name: "React" },
  //     { name: "Redux-Toolkit" },
  //     { name: "Bootstrap5" },
  //     { name: "Javascript" },
  //     { name: "CSS3" },
  //     { name: "React Bootstrap" },
  //     { name: "React Hook Form" },
  //     { name: "React Router" },
  //     { name: "React-Icons" },
  //     { name: "Sweet-Alert" },
  //     { name: "Axios" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Draw.io" },
  //     { name: "NodeJS" },
  //     { name: "ExpressJS" },
  //     { name: "MongoDB" },
  //     { name: "Postman" },
  //     { name: "Netlify" },
  //     { name: "Render" },
  //     { name: "Trello" },
  //     { name: "Scrum" },
  //   ],
  //   responsabilities: [
  //     "Scrummaster: definición de sprints, organización del backlog y descripción de tareas.",
  //     "Mockups de interfaces con Draw.io.",
  //     "Definición de requerimientos de usuario",
  //     "Colaboración en desarrollo responsive de toda la aplicación.",
  //     "Maquetado de páginas: Profesionales, Opciones de Registro, Publicaciones, Quienes Somos, Soporte Admin, Sidebar.",
  //     "Funcionalidades: Visualización de comentarios, eliminación de comentarios como admin, creación de publicaciones y perfil profesional.",
  //     "Implementación de buenas prácticas semánticas",
  //     "Resolución de issues en github",
  //     "Implementación de lineamientos de arquitectura basada en dominios",
  //   ],
  //   characteristics: [
  //     "Aplicación de Metodología Scrum",
  //     "Arquitectura basada en dominios",
  //   ],
  //   features: [
  //     "Registro e inicio de sesión de usuarios",
  //     "Visualización de anuncios de profesionales",
  //     "Paginación para anuncios de profesionales",
  //     "Visualización detallada de anuncio de profesional",
  //     "Gestión de perfil para profesionales",
  //     "Gestión de publicaciones para profesionales",
  //     "Filtrado de profesionales por nombre, ubicación y categoría",
  //     "Publicación de comentario y valoración para clientes",
  //     "Envío de mensajes de soporte para profesionales",
  //     "Gestión de mensajes reportados por profesionales",
  //     "Gestión de usuarios y categorías",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/LaburandoAndo",
  //   link: "https://laburando-ando.netlify.app/",
  // },
  {
    id: 666,
    image: imgtfi,
    category: "Documentación",
    name: "Sistema de Gestión de Reservas - Hostal San Jorge",
    type: "Análisis y Diseño de sistemas",
    area: "académico",
    date: "Noviembre 2020",
    duration: "5 meses",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Proyecto académico orientado al diseño de un sistema de gestión de reservas para el Hostal San Jorge. Incluye análisis de requerimientos, casos de uso, modelado UML, diseño de base de datos y prototipos de interfaz.",
    technologies: [
      { name: "Análisis de requerimientos" },
      { name: "Casos de uso" },
      { name: "Modelado UML" },
      { name: "Modelado de base de datos" },
      { name: "Prototipos de interfaz" },
      { name: "Draw.io" },
      { name: "Documentación técnica" },
      { name: "Balsamiq" },
    ],
    responsabilities: [
      "Relevamiento de requerimientos.",
      "Redacción de casos de uso y contratos",
      "Diagramas UML: diagrama de casos de uso, modelo de dominio, diagrama de actividades, diagrama de clases, diagramas de secuencia, diagramas de colaboración, diagrama de transición de estados.",
      "Modelado de base de datos (Modelo Entidad-Relación y Modelo relacional).",
      "Diseño de prototipos de interfaz del sistema.",
      "Contribución a la documentación general del proyecto final.",
    ],
    features: [],
    characteristics: [
      "Sistema propuesto para gestionar reservas, clientes y habitaciones.",
      "Casos de uso detallados para cada módulo del sistema.",
      "Modelos UML completos para visualizar procesos y entidades.",
    ],
    video: "",
    file: tfi,
    github: "",
    link: "",
  },
  {
    id: 779,
    image: lavanderia,
    category: "Lavandería",
    name: "API Restful para Lavanderías",
    type: "API REST",
    area: "backend",
    date: "Noviembre 2025",
    duration: "-",
    last_update: "Enero 2026",
    status: "En pausa",
    project: "Freelance",
    problem:
      "La gestión manual o fragmentada de órdenes, prendas, clientes y comprobantes dificulta el seguimiento del trabajo y puede generar demoras o inconsistencias en la atención.",
    outcome:
      "La API proporciona una base centralizada y escalable para administrar la operación, con autenticación, validaciones, manejo de errores y generación de comprobantes.",
    outcomeLabel: "Impacto esperado",
    outcomeDetail:
      "Integrada en un negocio, permitiría reducir la duplicación de datos, automatizar tareas administrativas y mantener un historial confiable de clientes y órdenes.",
    description:
      "API RESTful desarrollada para la gestión interna de lavanderías. En esta API se pueden gestionar órdenes, prendas, clientes y usuarios administradores, generación de remitos mediante Pureimage y almacenamiento con Cloudinary, autenticación segura y validaciones robustas. La API está diseñada para optimizar las operaciones diarias de una lavandería. Se encuentra en continuo desarrollo para agregar nuevas funcionalidades según las necesidades del cliente.",
    technologies: [
      { name: "Node js" },
      { name: "Express js" },
      { name: "Express validator" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Postman" },
      { name: "JSON Web Token" },
      { name: "Cloudinary" },
      { name: "Bcrypt" },
      { name: "Pureimage" },
    ],
    responsabilities: [
      "Implementación de rutas, controladores, servicios, repositorios y valiaciones para ordenes, prendas, clientes y usuarios administradores.",
      "Gestión de autenticación y autorización de usuarios administradores.",
      "Validación de datos y manejo de errores.",
      "Pruebas de API con Postman y documentación de endpoints.",
    ],
    features: [
      "CRUD de ordenes, prendas, clientes y usuarios.",
      "Autenticación con tokens JWT.",
      "Endpoints organizados y documentados para fácil integración con frontend.",
      "Validaciones y manejo de errores completo.",
    ],
    characteristics: [],
    video: "",
    github: "",
    link: "",
  },
  {
    id: 770,
    image: alojamientos,
    category: "Alojamientos",
    name: "API Restful para Alojamientos",
    type: "API REST",
    area: "backend",
    date: "Marzo 2026",
    duration: "-",
    last_update: "-",
    status: "En pausa",
    project: "Freelance",
    problem:
      "Los alojamientos suelen gestionar reservas, estadías, pagos, habitaciones y huéspedes mediante herramientas separadas, lo que dificulta tener una visión completa de la operación.",
    outcome:
      "La API fue diseñada para centralizar los principales procesos de un alojamiento y servir como base tanto para la gestión interna como para futuras reservas online.",
    outcomeLabel: "Impacto esperado",
    outcomeDetail:
      "En una implementación real, ayudaría a reducir errores de disponibilidad, agilizar el registro de reservas y pagos, mejorar el seguimiento de cada estadía y disponer de información organizada para tomar decisiones.",
    description:
      "API RESTful desarrollada para la gestión interna de alojamientos. En esta API se pueden gestionar servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes, administradores y autenticación para administradores y huéspedes. La API está diseñada para optimizar todos los procesos de un alojamiento. Además también permitirá que los usuarios puedan realizar reservas. Se encuentra en continuo desarrollo para agregar nuevas funcionalidades como reportes, gestión de stock, gestión de promociones/descuentos, notificaciones, turnos para el desayuno, entre otras.",
    technologies: [
      { name: "Node js" },
      { name: "Express js" },
      { name: "Express validator" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Postman" },
      { name: "JSON Web Token" },
      { name: "Nodemailer" },
      { name: "Cloudinary" },
      { name: "MercadoPago" },
      { name: "Stripe" },
    ],
    responsabilities: [
      "Implementación de rutas, controladores, servicios, repositorios y valiaciones para autenticación, servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes y usuarios administradores.",
      "Gestión de autenticación y autorización de usuarios administradores y huéspedes.",
      "Validación de datos y manejo de errores.",
      "Pruebas de API con Postman y documentación de endpoints.",
    ],
    features: [
      "CRUD de servicios/comodidades, habitaciones, tipos de habitaciones, reservas, estadías, pagos, métodos de pago, canales de reservas, huéspedes y usuarios.",
      "Autenticación con tokens JWT.",
      "Endpoints organizados y documentados para fácil integración con frontend.",
      "Validaciones y manejo de errores completo.",
    ],
    characteristics: [],
    video: "",
    github: "",
    link: "",
  },
  // {
  //   id: 777,
  //   image: ab,
  //   category: "Restaurante",
  //   name: "API Restful Restaurante Ambiente Bohemio",
  //   type: "API REST",
  //   area: "backend",
  //   date: "Marzo 2024",
  //   duration: "4 semanas",
  //   last_update: "Octubre 2025",
  //   status: "Actualizando",
  //   project: "Educativo",
  //   description:
  //     "API RESTful desarrollada para gestionar un restaurante, incluyendo usuarios, productos, pedidos y autenticación, con buenas prácticas de organización de rutas y controladores.",
  //   technologies: [
  //     { name: "Node js" },
  //     { name: "Express js" },
  //     { name: "Express-validator" },
  //     { name: "MongoDB" },
  //     { name: "Mongoose" },
  //     { name: "Javascript" },
  //     { name: "Git" },
  //     { name: "Github" },
  //     { name: "Postman" },
  //     { name: "JSON Web Token" },
  //     { name: "Bcrypt" },
  //     { name: "Vercel"}
  //   ],
  //   responsabilities: [
  //     "Implementación de rutas y controladores para usuarios, productos y pedidos.",
  //     "Gestión de autenticación y autorización de usuarios.",
  //     "Validación de datos y manejo de errores.",
  //     "Pruebas de API con Postman y documentación de endpoints.",
  //   ],
  //   features: [
  //     "CRUD de usuarios, productos y pedidos.",
  //     "Autenticación con tokens JWT.",
  //     "Endpoints organizados y documentados para fácil integración con frontend.",
  //     "Validaciones y manejo de errores completo.",
  //   ],
  //   characteristics: [
  //     "Aplicación de Metodología Scrum",
  //     "Despliegue en Vercel",
  //   ],
  //   video: "",
  //   github: "https://github.com/brunomry/API_restaurante",
  //   link: "",
  // },

  {
    id: 888,
    image: netflixcard,
    category: "Interfaz mobile en Figma",
    name: "Vista principal Instagram - Netflix",
    type: "Diseño UI",
    area: "diseño",
    date: "Mayo 2025",
    duration: "1 semana",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Desafío de diseño propuesto en curso de youtube sobre Figma brindado por uxcristopher que consistía en diseñar la interfaz principal de Instagram y Netflix.",
    technologies: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilities: [
      "Primeros diseños en Figma",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño replicado de aplicaciones reconocidas (Netflix/Instagram)",
    ],
    features: [],
    characteristics: [
      "Diseño de interfaz principal de Instagram y Netflix",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    video: "",
    github: "",
    images: [ig, netflix],
    link: "https://www.figma.com/design/2DxaPRLCWwSmJjCte0qdm8/Dise%C3%B1os?node-id=0-1&t=iT0lRymaWSvM4QJJ-1",
  },
  {
    id: 999,
    image: buenbitcard,
    category: "Interfaz mobile en Figma",
    name: "Vista Home - App BuenBit",
    type: "Diseño UI",
    area: "diseño",
    date: "Agosto 2025",
    duration: "3 días",
    last_update: "-",
    status: "Finalizado",
    project: "Educativo",
    description:
      "Desafío de diseño propuesto por BuenBit que consistía en realizar un diseño original de la Home de su aplicación y publicarlo en X con el hashtag #FigmaEnBuenBit. El desafío estaba pensado para diseñadores pero cualquier persona podía participar.",
    technologies: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilities: [
      "Desafío de diseño",
      "Publicación en X con hashtag #FigmaEnBuenBit",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño inspirado en la Home de app BuenBit",
    ],
    features: [],
    characteristics: [
      "Diseño de la Home de BuenBit",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    images: [buenbit],
    video: "",
    github: "",
    link: "https://www.figma.com/design/joPj1Ky1SUs3O37tQVotqg/HomeBuenbit?node-id=1-689&t=ar7HVNYCBf2uByns-1",
  },
];

export default projects;
