import laburandoando from "../assets/proyectos/laburandoando.png";
import ab from "../assets/proyectos/ambientebohemio.webp";
import temp from "../assets/proyectos/temp.webp";
import rss1 from "../assets/proyectos/rss1.webp";
import blogrecetas from "../assets/proyectos/blogrecetas.webp";
import sanjorge from "../assets/proyectos/sanjorge.webp";
import wpp from "../assets/proyectos/wpp.webp";

const proyectos = [
  {
    id: 111,
    imagen: laburandoando,
    categoria:"Portal de trabajo",
    nombre: "LaburandoAndo",
    tipo: "Aplicación web",
    fecha: "Julio 2024",
    duracion: "6 semanas",
    ultima_actualizacion: "-",
    descripcion:
      "LaburandoAndo es una plataforma web diseñada para conectar a trabajadores independientes con clientes que necesitan sus servicios. La aplicación permite a los profesionales crear y gestionar sus perfiles, publicar anuncios de trabajo y recibir opiniones de sus clientes. Los usuarios pueden buscar y filtrar profesionales por categorías, ver detalles de sus servicios y contratar directamente desde la plataforma. Proyecto final correspondiente al curso Especialización en React. Nota: El backend fue desplegado con Render por lo que es posible que debas esperar algunos minutos para poder ver los anuncios de trabajo en la página de Profesionales.",
    proyecto: "En equipo",
    responsabilidades: [
      "Desempeñé rol de Scrummaster (definición de sprints y organización de backlog, completar descripciones de tareas, colaborar y resolver cuestiones relacionadas al maquetado, guiar al equipo)",
      "Realicé los mockups de interfaces de toda la aplicación mediante la herramienta Draw.io.",
      "Colaboré en la definición de requerimientos.",
      "Colaboré en el desarrollo de todas las páginas realizando las correcciones pertinentes y verificando que cumplan con un diseño web responsive",
      "Desarrollé las páginas de Profesionales, Opciones de Registro, Quiénes Somos, Perfil Profesional, Publicación del profesional, Publicaciones del profesional, Soporte Admin, Categorías Admin, y Menú Lateral.",
      "Desarrollé la funcionalidad para mostrar y agregar comentarios en el detalle de anuncio, eliminar comentarios como administrador, crear publicación como profesional, mostrar publicaciones en perfil profesional, mostrar mensajes en Soporte Admin",
      "Implementé buenas prácticas de SEO",
      "Colaboré en el desarrollo de funcionalidad de iniciar sesión."
    ],
    github: "https://github.com/brunomry/LaburandoAndo",
    enlace: "https://laburando-ando.netlify.app/",
    tecnologias: [
      { name: "CSS3" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "React" },
      { name: "React-Bootstrap" },
      { name: "React-Hook-Form" },
      { name: "React-Router" },
      { name: "Redux-Toolkit"},
      { name: "Axios" },
      { name: "Git" },
      { name: "Github"},
      { name: "Trello" },
      { name: "Draw"},
      { name: "NodeJS"},
      { name: "ExpressJS" },
      { name: "MongoDB" },
      { name: "Postman"},
      { name: "Netlify"},
      { name: "Render"},
    ],
  },
  {
    id: 123,
    imagen: ab,
    categoria:"Restaurante",
    nombre: "Ambiente Bohemio",
    tipo: "Aplicación web",
    fecha: "Marzo 2024",
    duracion: "4 semanas",
    ultima_actualizacion: "Marzo 2025",
    descripcion:
      "Aplicación web de Restaurante donde el objetivo principal consistía en que los usuarios luego de registrarse e iniciar sesión puedan realizar un pedido. Como funcionalidad extra se integró la API de MercadoPago para realizar el pago de pedidos. Proyecto final correspondiente al curso Desarrollador Full Stack.",
    proyecto: "En equipo",
    responsabilidades: [
      "Desempeñé rol de scrummaster (organización de backlog, completar descripciones de tareas, establecer prioridad a tareas, colaborar y resolver cuestiones relacionadas al maquetado, guiar al equipo)",
      "Realicé mejoras significativas de diseño en todas las páginas de la aplicación, modifiqué funcionalidad de proceso de pago y estructura de proyecto (octubre 2024).",
      "Realicé los mockups de interfaces de toda la aplicación mediante la herramienta Draw.io.",
      "Desarrollé las páginas de Inicio, Detalle de producto, Administración, Detalle de compra, Historial de pedidos.",
      "Desarrollé la funcionalidad de listar productos por categoría, filtrar productos por nombre y descarga de PDF en página de Menú, entre otras.",
      "Colaboré en el desarrollo de la funcionalidad de pago integrando la API de MercadoPago."
    ],
    github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
    enlace: "https://ambiente-bohemio-restaurante.netlify.app/",
    tecnologias: [
      { name: "CSS3" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "React" },
      { name: "React-Bootstrap" },
      { name: "React-Hook-Form"},
      { name: "React-Router"},
      { name: "NodeJS"},
      { name: "ExpressJS" },
      { name: "MongoDB" },
      { name: "Git" },
      { name: "Github" },
      { name: "Trello" },
      { name: "Draw" },
      { name: "Postman"}
    ],
  },
  {
    id: 222,
    imagen: sanjorge,
    categoria: "Hostal",
    nombre: "Hostal San Jorge",
    tipo: "Aplicación web",
    fecha: "Enero 2024",
    duracion: "8 semanas",
    ultima_actualizacion: "Febrero 2025",
    descripcion:
      "Este proyecto nace con el objetivo de establecer la presencia en línea del Hostal San Jorge, ubicado en Cafayate, Salta, Argentina. La necesidad de un sitio web surgió para mejorar su visibilidad y atraer a más clientes potenciales, donde los usuarios puedan informarse sobre los servicios del hostal, consultar la disponibilidad de habitaciones y realizar reservas. Como primera versión desarrollé un sitio web utilizando las tecnologías de HTML5, CSS3, Bootstrap5 y Javascript. Actualmente desarrollé la segunda versión en este caso migrando el sitio hacia una aplicación web de React y Tailwind donde modifiqué el diseño de las páginas para que luzca más moderno, realicé la optimización SEO mediante la librería react-helmet y otras herramientas, las funcionalidades de traducción de español a inglés, además de formulario de contacto y formulario de reserva usando Nodemailer. En una siguiente versión añadiré la funcionalidad de reserva de habitaciones que permitirá a los usuarios seleccionar fechas de estadía y confirmar su reserva, integrando métodos de pago online.",
    proyecto: "Freelance",
    responsabilidades: [
      "Logré posicionar el sitio en los primeros resultados de búsqueda en Google mediante palabras clave como “hostal san jorge”, “hostal san jorge cafayate” y ”san jorge cafayate”.",
      "Implementé técnicas para optimizar la velocidad y el rendimiento de la aplicación.",
      "Incorporé contacto directo vía WhatsApp, además de formularios de contacto y reserva para que los usuarios realicen consultas y solicitudes de reserva.",
      "Implementé traducción de español a inglés para todas las páginas de la aplicación.",
      "Vinculé la aplicación web con la opción de 'Sitio web' para negocios registrados en Google.",
      "Trabajé con una fotógrafa para obtener imágenes de alta calidad que destacan los espacios y servicios del hostal."
    ],
    github: "https://github.com/brunomry/HostalSanJorgeCafayate",
    enlace: "https://hostalsanjorgecafayate.netlify.app/",
    tecnologias: [
      { name: "CSS3" },
      { name: "Javascript" },      
      { name: "React" },
      { name: "Tailwind" },
      { name: "React-Hook-Form" },
      { name: "React-Router" },
      { name: "Git" },
      { name: "Github" },
      { name: "Netlify"},
    ],
  },
  {
    id: 333,
    imagen: blogrecetas,
    nombre: "Blog de recetas",
    categoria: "Blog",
    tipo: "Aplicación web",
    fecha: "Febrero 2024",
    duracion: "10 días",
    ultima_actualizacion: "-",
    descripcion:
      "Aplicación web sobre Blog de recetas donde el objetivo principal consistía en que el administrador pueda iniciar sesión y gestionar las recetas. El proyecto comenzó siendo en equipo desarrollándose todo el frontend y su continuación consistía en desarrollar de forma individual el backend de la aplicación.",
    proyecto: "En equipo",
    responsabilidades: ["Realicé los mockups de interfaces mediante la herramienta Draw.io","Desarrollé la página de detalle de receta", "Desarrollé menú de navegación y pie de página", "Desarrollé el backend de la aplicación"],
    github: "https://github.com/brunomry/frontendBlogDeRecetas",
    enlace: "https://rincondeplaceresgastronomicos-rpg.netlify.app/",
    tecnologias: [
      { name: "CSS3" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "React" },
      { name: "React-Bootstrap" },
      { name: "React-Hook-Form" },
      { name: "React-Router"},
      { name: "Node JS" },
      { name: "Express JS" },
      { name: "MongoDB" },
      { name: "Git" },
      { name: "Github" },
      { name: "Draw" },
    ],
  },
  {
    id: 444,
    imagen: temp,
    nombre: "Temporizador",
    categoria: "Temporizador",
    tipo: "Aplicación web",
    fecha: "Diciembre 2023",
    duracion: "1 semana",
    ultima_actualizacion: "Julio 2024",
    descripcion: "El proyecto realizado es una aplicación web de temporizador donde el objetivo consistía en desarrollar las funcionalidades de iniciar, pausar, continuar y restablecer el temporizador. ",
    proyecto: "Individual",
    responsabilidades: ["El diseño fue replicado de una aplicación existente.", "Agregué en el menú de navegación las opciones para redirigir a aplicaciones desarrolladas de reloj y cronómetro."],
    github: "https://github.com/brunomry/Temporizador",
    enlace: "https://temporizador-online-bmr.netlify.app/",
    tecnologias: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
    ],
  },
  {
    id: 666,
    imagen: rss1,
    nombre: "Rolling Shoes Store",
    categoria: "E-Commerce estático",
    tipo: "Sitio web",
    fecha: "Octubre 2023",
    duracion:"2 semanas",
    ultima_actualizacion: "Diciembre 2024",
    descripcion: "El proyecto realizado es un sitio web de tienda de calzados donde el objetivo consistía en desarrollar un E-commerce estático donde se visualice toda la información relacionada a los productos y cuente además con un carrito de compras.",
    proyecto: "En equipo",
    responsabilidades: ["Realicé los mockups de interfaces mediante Draw.io","Desarrollé las páginas de contacto, carrito de compras y detalle de producto", "Desarrollé menú de navegación", "Realicé mejoras de diseño en todas las páginas (diciembre 2024)"],
    github: "https://github.com/brunomry/RollingShoesStore",
    enlace: "https://rollingshoesstore-rss.netlify.app/",
    tecnologias: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "Bootstrap5" },
      { name: "Trello" },
      { name: "Draw" },
    ],
  },
  {
    id: 1267,
    imagen: wpp,
    nombre: "WhatsApp Web",
    categoria: "Interfaz WhatsApp web",
    tipo: "Challenge",
    fecha: "Mayo 2024",
    duracion: "1 semana",
    ultima_actualizacion: "-",
    descripcion: "Challenge propuesto por RollingCodeSchool donde el objetivo consistía en replicar la vista de WhatsApp web al menos para desktop utilizando HTML5 y CSS3.",
    proyecto: "Individual",
    responsabilidades: ["Buenas prácticas de SEO", "HTML semántico", "Buenas prácticas de código", "Uso de metodología BEM", "Diseño fiel"],
    github: "https://github.com/brunomry/challengeRollingCode",
    enlace: "https://challenge-rc-bmr.netlify.app/",
    tecnologias: [
      { name: "HTML5" },
      { name: "CSS3" },
    ],
  }
];

export default proyectos;
