import laburandoando from "../assets/proyectos/laburandoando.png";
import ab from "../assets/proyectos/ambientebohemio.webp";
import sanjorge from "../assets/proyectos/sanjorge.webp";
import rafter from "../assets/proyectos/rafter.webp";

const proyectos = [
  {
    id: 223,
    imagen: rafter,
    categoria: "Construcción",
    nombre: "Rafter Constructora",
    tipo: "Landing page",
    area: "frontend",
    fecha: "Septiembre 2025",
    duracion: "2 semanas",
    ultima_actualizacion: "Octubre 2025",
    estado: "En proceso",
    proyecto: "Freelance",
    descripcion:
      "Landing page desarrollada para empresa de construcción de San Miguel de Tucumán con diseño moderno, responsive y optimización SEO.",
    tecnologias: [
      { name: "Figma" },
      { name: "React" },
      { name: "Tailwind" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Hostinger" },
    ],
    responsabilidades: [
      "Diseño de interfaces con Figma",
      "Posicionamiento en Google con palabras clave relevantes",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de dominio y hosting mediante Hostinger"
    ],
    features: [
      "Diseño responsive con Tailwind",
      "Optimización SEO para buscadores",
    ],
    video: "",
    github: "",
    enlace: "https://rafterconstructora.netlify.app/",
  },
  {
    id: 222,
    imagen: sanjorge,
    categoria: "Hostal",
    nombre: "Hostal San Jorge",
    tipo: "Aplicación web",
    area: "frontend",
    fecha: "Enero 2024",
    duracion: "8 semanas",
    ultima_actualizacion: "Febrero 2025",
    estado: "Actualizando",
    proyecto: "Freelance",
    descripcion:
      "Aplicación web para mejorar la visibilidad online del Hostal San Jorge de Cafayate, donde los usuarios pueden informarse sobre habitaciones, servicios, realizar solicitudes de reservas mediante formulario y consultas por WhatsApp o formulario de contacto.",
    tecnologias: [
      { name: "React" },
      { name: "Tailwind" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Netlify" },
    ],
    responsabilidades: [
      "Posicionamiento en Google con palabras clave relevantes",
      "Optimización de velocidad y rendimiento de la app",
      "Formularios de contacto y reserva para usuarios",
      "Implementación de traducción de español a inglés",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de imágenes de alta calidad con fotógrafa",
    ],
    features: [
      "Consulta de habitaciones por WhatsApp",
      "Formulario de reservas online",
      "Traducción de contenido a inglés",
      "Formulario de contacto integrado",
      "Optimización SEO y rendimiento de la app",
    ],
    video: "",
    github: "",
    enlace: "https://hostalsanjorgecafayate.netlify.app/",
  },
  {
    id: 123,
    imagen: ab,
    categoria: "Restaurante",
    nombre: "Ambiente Bohemio",
    tipo: "Aplicación web",
    area: "frontend",
    fecha: "Marzo 2024",
    duracion: "4 semanas",
    ultima_actualizacion: "Marzo 2025",
    estado: "Actualizando",
    proyecto: "Educativo",
    descripcion:
      "Aplicación web para restaurante donde los usuarios se registran, inician sesión y realizan pedidos online con integración de pago.",
    tecnologias: [
      { name: "React" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Bootstrap" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "NodeJS" },
      { name: "ExpressJS" },
      { name: "MongoDB" },
      { name: "Git" },
      { name: "Github" },
      { name: "Trello" },
      { name: "Draw" },
      { name: "Postman" },
    ],
    responsabilidades: [
      "Rol de scrummaster: organización de backlog, descripción de tareas y guía del equipo.",
      "Mejoras de diseño, funcionalidad de pago y estructura de proyecto (octubre 2024).",
      "Mockups de interfaces con Draw.io.",
      "Desarrollo de páginas Inicio, Detalle producto, Administración, Historial de pedidos.",
      "Listado de productos por categoría, filtrado por nombre, descarga de PDF en menú.",
      "Integración de la API de MercadoPago para pagos.",
    ],
    features: [
      "Registro e inicio de sesión de usuarios",
      "Carrito de compras y pago con MercadoPago",
      "Filtrado de productos por categoría o nombre",
      "Descarga de PDF del menú",
      "Backend con despliegue en Vercel y API en Node/Express",
    ],
    video: "",
    github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
    enlace: "https://ambiente-bohemio-restaurante.netlify.app/",
  },

  {
    id: 111,
    imagen: laburandoando,
    categoria: "Portal de Trabajo",
    nombre: "LaburandoAndo",
    tipo: "Aplicación web",
    area: "frontend",
    fecha: "Julio 2024",
    duracion: "6 semanas",
    ultima_actualizacion: "-",
    estado: "Finalizado",
    proyecto: "Educativo",
    descripcion:
      "Plataforma web que conecta trabajadores independientes con clientes para publicar y contratar servicios.",
    tecnologias: [
      { name: "React" },
      { name: "Redux-Toolkit" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Bootstrap" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Axios" },
      { name: "Git" },
      { name: "Github" },
      { name: "Trello" },
      { name: "Draw" },
      { name: "NodeJS" },
      { name: "ExpressJS" },
      { name: "MongoDB" },
      { name: "Postman" },
      { name: "Netlify" },
      { name: "Render" },
    ],
    responsabilidades: [
      "Scrummaster: definición de sprints y organización del backlog.",
      "Mockups de interfaces con Draw.io.",
      "Definición de requerimientos y colaboración en desarrollo responsive.",
      "Páginas: Profesionales, Registro, Publicaciones, Soporte Admin.",
      "Funcionalidad de comentarios, creación de publicaciones y perfil profesional.",
      "Buenas prácticas de SEO implementadas.",
    ],
    features: [
      "Registro e inicio de sesión de usuarios",
      "Creación, edición y visualización de perfiles profesionales",
      "Publicación de anuncio de profesionales",
      "Filtrado de profesionales por nombre, ubicación y categoría",
      "Sistema de comentarios para clientes",
      "Backend con despliegue en Render y API en Node/Express",
    ],
    video: "",
    github: "https://github.com/brunomry/LaburandoAndo",
    enlace: "https://laburando-ando.netlify.app/",
  },
];

export default proyectos;
