import laburandoando from "../assets/proyectos/laburandoando.png";
import ab from "../assets/proyectos/ambientebohemio.webp";
import sanjorge from "../assets/proyectos/sanjorge.webp";
import rafter from "../assets/proyectos/rafter.webp";
import imgtfi from "../assets/proyectos/tfi.png";
import ig from "../assets/proyectos/ig.png";
import netflixcard from "../assets/proyectos/netflixcard.png";
import netflix from "../assets/proyectos/netflix.png";
import buenbit from "../assets/proyectos/buenbit.png";
import buenbitcard from "../assets/proyectos/buenbitcard.png";

import tfi from "../assets/proyectos/trabajofinal-diseñodesistemas.pdf";

const proyectos = [
  {
    id: 223,
    imagen: rafter,
    categoria: "Construcción",
    nombre: "Rafter Constructora",
    tipo: "Landing page",
    area: "frontend",
    fecha: "Septiembre 2025",
    duracion: "2 semanas",
    ultima_actualizacion: "Octubre 2025",
    estado: "En proceso",
    proyecto: "Freelance",
    descripcion:
      "Landing page desarrollada para empresa de construcción de San Miguel de Tucumán con diseño moderno, responsive y optimización SEO.",
    tecnologias: [
      { name: "Figma" },
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Hostinger" },
      { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
    ],
    responsabilidades: [
      "Diseño de interfaz con Figma",
      "Posicionamiento en Google con palabras clave relevantes",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de dominio y hosting mediante Hostinger",
    ],
    caracteristicasProyecto: [
      "Diseño responsive con Tailwind",
      "Optimización SEO para buscadores",
    ],
    features: [],
    video: "",
    github: "",
    enlace: "https://rafterconstructora.netlify.app/",
  },
  {
    id: 222,
    imagen: sanjorge,
    categoria: "Alojamiento",
    nombre: "Hostal San Jorge",
    tipo: "Sitio web",
    area: "frontend",
    fecha: "Enero 2024",
    duracion: "8 semanas",
    ultima_actualizacion: "Noviembre 2025",
    estado: "Actualizando",
    proyecto: "Freelance",
    descripcion:
      "Sitio web para mejorar la visibilidad online del Hostal San Jorge de Cafayate, donde los usuarios pueden informarse sobre habitaciones, servicios, realizar solicitudes de reservas mediante formulario y consultas por WhatsApp o formulario de contacto.",
    tecnologias: [
      { name: "React" },
      { name: "TailwindCSS" },
      { name: "SEO" },
      { name: "Javascript" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "CSS3" },
      { name: "Git" },
      { name: "Github" },
      { name: "Netlify" },
      { name: "Google Search Console" },
      { name: "PageSpeed Insights" },
    ],
    responsabilidades: [
      "Posicionamiento en Google con palabras clave relevantes",
      "Optimización de velocidad y rendimiento de la app",
      "Formularios de contacto y reserva para usuarios",
      // "Implementación de traducción de español a inglés",
      "Integración con 'Sitio web' de Google My Business",
      "Gestión de imágenes de alta calidad con fotógrafa",
      "Buenas prácticas semánticas",
    ],
    caracteristicasProyecto: [
      "Optimización SEO y rendimiento de la app",
      "Registro de dominio en Google Search Console",
      "Contratación de fotógrafa",
    ],
    features: [
      "Formulario de reserva",
      "Formulario de contacto",
      "Consultas por WhatsApp",
      // "Traducción de contenido a inglés",
    ],
    video: "",
    github: "",
    enlace: "https://hostalsanjorgecafayate.netlify.app/",
  },
  {
    id: 123,
    imagen: ab,
    categoria: "Restaurante",
    nombre: "Ambiente Bohemio",
    tipo: "Aplicación web",
    area: "frontend",
    fecha: "Marzo 2024",
    duracion: "4 semanas",
    ultima_actualizacion: "Marzo 2025",
    estado: "Actualizando",
    proyecto: "Educativo",
    descripcion:
      "Aplicación web para restaurante donde los usuarios se registran, inician sesión y realizan pedidos online con integración de pago.",
    tecnologias: [
      { name: "React" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Bootstrap" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "Sweet-Alert" },
      { name: "Node js" },
      { name: "Express js" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "Git" },
      { name: "Github" },
      { name: "Trello" },
      { name: "Scrumban" },
      { name: "Draw.io" },
      { name: "Postman" },
    ],
    responsabilidades: [
      "Rol de scrummaster: organización de backlog, descripción de tareas y guía del equipo.",
      "Mejoras de diseño, funcionalidad de pago y estructura de proyecto (octubre 2024).",
      "Mockups de interfaces con Draw.io.",
      "Maquetado de páginas: Inicio, Detalle producto, Administración, Historial de pedidos.",
      "Funcionalidades: listado de productos por categoría, filtrado por nombre, descarga de PDF en menú.",
      "Colaboración en integración de API de MercadoPago para pagos.",
    ],
    caracteristicasProyecto: ["Aplicación de Metodología Scrumban"],
    features: [
      "Registro e inicio de sesión de usuarios",
      "Visualización de productos",
      "Carrito de compras y pago con MercadoPago",
      "Filtrado de productos por categoría o nombre",
      "Descarga de PDF del menú",
      "Gestión de usuarios, productos y pedidos",
      "Backend con despliegue en Vercel y API en Node/Express",
    ],
    video: "",
    github: "https://github.com/brunomry/frontendProyectoFinal_RollingCode",
    enlace: "https://ambiente-bohemio-restaurante.netlify.app/",
  },

  {
    id: 111,
    imagen: laburandoando,
    categoria: "Portal de Trabajo",
    nombre: "LaburandoAndo",
    tipo: "Aplicación web",
    area: "frontend",
    fecha: "Julio 2024",
    duracion: "6 semanas",
    ultima_actualizacion: "-",
    estado: "Finalizado",
    proyecto: "Educativo",
    descripcion:
      "Esta idea de proyecto surge de la necesidad de contar con un portal específico que pueda reunir una amplia variedad de trabajos autónomos, brindando visibilidad y oportunidades a profesionales independientes que buscan ampliar su clientela y conectar con nuevos clientes. La aplicación está diseñada para facilitar la búsqueda y contratación de servicios.",
    tecnologias: [
      { name: "React" },
      { name: "Redux-Toolkit" },
      { name: "Bootstrap5" },
      { name: "Javascript" },
      { name: "CSS3" },
      { name: "React Bootstrap" },
      { name: "React Hook Form" },
      { name: "React Router" },
      { name: "React-Icons" },
      { name: "Sweet-Alert" },
      { name: "Axios" },
      { name: "Git" },
      { name: "Github" },
      { name: "Draw.io" },
      { name: "NodeJS" },
      { name: "ExpressJS" },
      { name: "MongoDB" },
      { name: "Postman" },
      { name: "Netlify" },
      { name: "Render" },
      { name: "Trello" },
      { name: "Scrum" },
    ],
    responsabilidades: [
      "Scrummaster: definición de sprints, organización del backlog y descripción de tareas.",
      "Mockups de interfaces con Draw.io.",
      "Definición de requerimientos de usuario",
      "Colaboración en desarrollo responsive de toda la aplicación.",
      "Maquetado de páginas: Profesionales, Opciones de Registro, Publicaciones, Quienes Somos, Soporte Admin, Sidebar.",
      "Funcionalidades: Visualización de comentarios, eliminación de comentarios como admin, creación de publicaciones y perfil profesional.",
      "Implementación de buenas prácticas semánticas",
      "Resolución de issues en github",
      "Implementación de arquitectura basada en dominios (DDD)",
    ],
    caracteristicasProyecto: [
      "Aplicación de Metodología Scrum",
      "Arquitectura basada en dominios",
    ],
    features: [
      "Registro e inicio de sesión de usuarios",
      "Visualización de anuncios de profesionales",
      "Paginación para anuncios de profesionales",
      "Visualización detallada de anuncio de profesional",
      "Gestión de perfil para profesionales",
      "Gestión de publicaciones para profesionales",
      "Filtrado de profesionales por nombre, ubicación y categoría",
      "Publicación de comentario y valoración para clientes",
      "Envío de mensajes de soporte para profesionales",
      "Gestión de mensajes reportados por profesionales",
      "Gestión de usuarios y categorías",
    ],
    video: "",
    github: "https://github.com/brunomry/LaburandoAndo",
    enlace: "https://laburando-ando.netlify.app/",
  },
  {
    id: 666,
    imagen: imgtfi,
    categoria: "Documentación",
    nombre: "Sistema de Gestión de Reservas - Hostal San Jorge",
    tipo: "Análisis y Diseño de sistemas",
    area: "universidad",
    fecha: "Noviembre 2020",
    duracion: "5 meses",
    ultima_actualizacion: "-",
    estado: "Finalizado",
    proyecto: "Educativo",
    descripcion:
      "Proyecto académico orientado al diseño de un sistema de gestión de reservas para el Hostal San Jorge. Incluye análisis de requerimientos, casos de uso, modelado UML, diseño de base de datos y prototipos de interfaz.",
    tecnologias: [
      { name: "Análisis de requerimientos" },
      { name: "Casos de uso" },
      { name: "Modelado UML" },
      { name: "Modelado de base de datos" },
      { name: "Prototipos de interfaz" },
      { name: "Draw.io" },
      { name: "Documentación técnica" },
      { name: "Balsamiq" },
    ],
    responsabilidades: [
      "Relevamiento de requerimientos.",
      "Redacción de casos de uso y contratos",
      "Diagramas UML: diagrama de casos de uso, modelo de dominio, diagrama de actividades, diagrama de clases, diagramas de secuencia, diagramas de colaboración, diagrama de transición de estados.",
      "Modelado de base de datos (Modelo Entidad-Relación y Modelo relacional).",
      "Diseño de prototipos de interfaz del sistema.",
      "Contribución a la documentación general del proyecto final.",
    ],
    features: [],
    caracteristicasProyecto: [
      "Sistema propuesto para gestionar reservas, clientes y habitaciones.",
      "Casos de uso detallados para cada módulo del sistema.",
      "Modelos UML completos para visualizar procesos y entidades.",
    ],
    video: "",
    archivo: tfi,
    github: "",
    enlace: "",
  },
  {
    id: 777,
    imagen: ab,
    categoria: "Restaurante",
    nombre: "API Restaurante Ambiente Bohemio",
    tipo: "API REST",
    area: "backend",
    fecha: "Marzo 2024",
    duracion: "4 semanas",
    ultima_actualizacion: "Octubre 2025",
    estado: "Actualizando",
    proyecto: "Educativo",
    descripcion:
      "API RESTful desarrollada para gestionar un restaurante, incluyendo usuarios, productos, pedidos y autenticación, con buenas prácticas de organización de rutas y controladores.",
    tecnologias: [
      { name: "Node js" },
      { name: "Express js" },
      { name: "Express-validator" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "Javascript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Postman" },
      { name: "JWT" },
    ],
    responsabilidades: [
      "Implementación de rutas y controladores para usuarios, productos y pedidos.",
      "Gestión de autenticación y autorización de usuarios.",
      "Validación de datos y manejo de errores.",
      "Pruebas de API con Postman y documentación de endpoints.",
    ],
    features: [
      "CRUD de usuarios, productos y pedidos.",
      "Autenticación con tokens JWT.",
      "Endpoints organizados y documentados para fácil integración con frontend.",
      "Validaciones y manejo de errores completo.",
    ],
    caracteristicasProyecto: ["Aplicación de Metodología Scrum", "Despliegue en Vercel"],
    video: "",
    github: "https://github.com/brunomry/API_restaurante",
    enlace: "",
  },
  {
    id: 888,
    imagen: netflixcard,
    categoria: "Interfaz mobile en Figma",
    nombre: "Vista principal Instagram - Netflix",
    tipo: "Diseño UI",
    area: "ui",
    fecha: "Mayo 2025",
    duracion: "1 semana",
    ultima_actualizacion: "-",
    estado: "Finalizado",
    proyecto: "Educativo",
    descripcion:
      "Desafío de diseño propuesto en curso de youtube sobre Figma brindado por uxcristopher que consistía en diseñar la interfaz principal de Instagram y Netflix.",
    tecnologias: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilidades: [
      "Primeros diseños en Figma",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño replicado de aplicaciones reconocidas (Netflix/Instagram)",
    ],
    features: [],
    caracteristicasProyecto: [
      "Diseño de interfaz principal de Instagram y Netflix",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    video: "",
    github: "",
    images: [ig, netflix],
    enlace:
      "https://www.figma.com/design/2DxaPRLCWwSmJjCte0qdm8/Dise%C3%B1os?node-id=0-1&t=iT0lRymaWSvM4QJJ-1",
  },
  {
    id: 999,
    imagen: buenbitcard,
    categoria: "Interfaz mobile en Figma",
    nombre: "Vista Home - App BuenBit",
    tipo: "Diseño UI",
    area: "ui",
    fecha: "Agosto 2025",
    duracion: "3 días",
    ultima_actualizacion: "-",
    estado: "Finalizado",
    proyecto: "Educativo",
    descripcion:
      "Desafío de diseño propuesto por BuenBit que consistía en realizar un diseño original de la Home de su aplicación y publicarlo en X con el hashtag #FigmaEnBuenBit. El desafío estaba pensado para diseñadores pero cualquier persona podía participar.",
    tecnologias: [
      { name: "Figma" },
      { name: "Atomic design" },
      { name: "Plugins" },
      { name: "Componentes reutilizables" },
      { name: "Tipografía" },
      { name: "Paleta de colores" },
    ],
    responsabilidades: [
      "Desafío de diseño",
      "Publicación en X con hashtag #FigmaEnBuenBit",
      "Creación de componentes reutilizables",
      "Práctica de metodología Atomic design",
      "Diseño inspirado en la Home de app BuenBit",
    ],
    features: [],
    caracteristicasProyecto: [
      "Diseño de la Home de BuenBit",
      "Aplicación de metodología Atomic Design",
      "Organización de componentes",
      "Interfaz mobile-first",
    ],
    images: [buenbit],
    video: "",
    github: "",
    enlace:
      "https://www.figma.com/design/joPj1Ky1SUs3O37tQVotqg/HomeBuenbit?node-id=1-689&t=ar7HVNYCBf2uByns-1",
  },
];

export default proyectos;
